import { VStack } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import AboutMe from "../components/about/AboutMe";
import AppShell from "../components/common/AppShell";
import NextButton from "../components/common/NextButton";

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>Michiel | About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell navVariant="black">
        <VStack spacing="16">
          <AboutMe>
            <NextButton>Career</NextButton>
          </AboutMe>
        </VStack>
      </AppShell>
    </>
  );
};

export default About;
