import type { NextPage } from "next";
import Head from "next/head";
import AppShell from "../components/common/AppShell";
import NextButton from "../components/common/NextButton";

const Career: NextPage = () => {
  return (
    <>
      <Head>
        <title>Career | Michiel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell variant="black">
        <NextButton to="/contact">Contact</NextButton>
      </AppShell>
    </>
  );
};

export default Career;
