import type { NextPage } from "next";
import Head from "next/head";
import AppShell from "../components/common/AppShell";

const Contact: NextPage = () => {
  return (
    <>
      <Head>
        <title>Contact | Michiel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell navVariant="black">Contact</AppShell>
    </>
  );
};

export default Contact;
