import Head from "next/head";
import {
  Box,
  HStack,
  ScaleFade,
  Text,
  useBreakpointValue,
  VStack,
} from "@chakra-ui/react";
import { Typewriter } from "react-simple-typewriter";
import Globe from "../../public/lottie/globe.json";
import AppShell from "../components/common/AppShell";
import Lottie from "lottie-react";
import NextButton from "../components/common/NextButton";

export default function Home() {
  const shouldRenderBreak = useBreakpointValue({
    base: "true",
    lg: false,
  });

  return (
    <>
      <Head>
        <title>Michiel Glibert</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell bg="#000020" navVariant="white">
        <VStack
          pos="relative"
          align="flex-start"
          justify="center"
          h="100%"
          spacing="16"
          maxW="7xl"
          margin="0 auto"
        >
          <Text color="white" fontSize="6xl" fontWeight="extrabold">
            Hi, I&apos;m Michiel,{shouldRenderBreak && <br />} a{" "}
            <Box as="span" color="#348AA7">
              <Typewriter
                words={[
                  "Software Engineer",
                  "Problem Solver",
                  "Tech Enthousiast",
                  "Team player",
                ]}
                cursor
                cursorColor="#348AA7"
                delaySpeed={2500}
                typeSpeed={45}
                deleteSpeed={45}
                loop={0}
              />
            </Box>
          </Text>
          <HStack spacing="12" align="flex-start">
            <VStack spacing="16" align="stretch">
              <Text color={"white"} maxW="2xl" fontSize="4xl">
                Pixel perfect, code clean, User-first, always keen. Front-end
                flows, design glows, Innovative solutions, always a pro.
              </Text>
              <NextButton variant="white">About me</NextButton>
            </VStack>
            <ScaleFade initialScale={0.3} in>
              <Box display={{ base: "none", xl: "block" }} mr="-36">
                <Lottie animationData={Globe} loop={true} />
              </Box>
            </ScaleFade>
          </HStack>
        </VStack>
      </AppShell>
    </>
  );
}
