import Head from "next/head";
import {
  Box,
  HStack,
  ScaleFade,
  Text,
  useBreakpointValue,
  VStack,
} from "@chakra-ui/react";
import { Typewriter } from "react-simple-typewriter";
import Globe from "../../public/lottie/globe.json";
import AppShell from "../components/common/AppShell";
import Lottie from "lottie-react";
import NextButton from "../components/common/NextButton";
import Greeting from "../components/home/Greeting";

export default function Home() {
  const shouldRenderBreak = useBreakpointValue({
    base: "true",
    lg: false,
  });

  return (
    <>
      <Head>
        <title>Michiel Glibert</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell bg="#000020" navVariant="white">
        <VStack
          pos="relative"
          align="flex-start"
          justify="center"
          h="100%"
          spacing="16"
          maxW="7xl"
          margin="0 auto"
        >
          <Greeting />
          <HStack spacing="12" align="flex-start">
            <VStack spacing="16" align="stretch">
              <Text color={"white"} maxW="2xl" fontSize="4xl">
                Pixel perfect, code clean, User-first, always keen. Front-end
                flows, design glows, Innovative solutions, always a pro.
              </Text>
              <NextButton to="/about" variant="white">
                About me
              </NextButton>
            </VStack>
            <ScaleFade initialScale={0.3} in>
              <Box display={{ base: "none", lg: "block" }} mr="-36">
                <Lottie animationData={Globe} loop={true} />
              </Box>
            </ScaleFade>
          </HStack>
        </VStack>
      </AppShell>
    </>
  );
}
