import Head from "next/head";
import { Manrope } from "@next/font/google";
import {
  Box,
  Center,
  GridItem,
  SimpleGrid,
  Text,
  useBreakpoint,
  useBreakpointValue,
} from "@chakra-ui/react";
import { Typewriter } from "react-simple-typewriter";
import Image from "next/image";

const inter = Manrope({ subsets: ["latin"] });

export default function Home() {
  const shouldRenderBreak = useBreakpointValue({
    base: "true",
    lg: false,
    xl: true,
    "2xl": false,
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <Center
          p="8"
          fontSize="5xl"
          fontWeight="bold"
          h="100vh"
          bg="radial-gradient(88.82% 88.82% at 6.6% 101.66%, #348AA7 0%, #102C4B 51.47%, #000020 99.52%)"
          pos="relative"
        >
          <SimpleGrid
            columns={12}
            w="100%"
            h="100%"
            columnGap={{ base: "0", xl: "16" }}
          >
            <GridItem
              gridColumn="span 5"
              alignSelf="flex-end"
              justifySelf="flex-end"
              zIndex={1}
              display={{ base: "none", xl: "block" }}
            >
              <Image
                src="/images/3d-male.png"
                width="440"
                height="200"
                alt="3D male"
              />
            </GridItem>

            <GridItem
              gridColumn={{ base: "span 12", xl: "span 7" }}
              alignSelf="flex-end"
              justifySelf={{ base: "center", xl: "flex-start" }}
              h="690"
              pt="24"
            >
              <Text align={{ base: "center", xl: "left" }} color="white">
                Hi, I&apos;m Michiel,{shouldRenderBreak && <br />} a{" "}
                <Box as="span" color="#348AA7">
                  <Typewriter
                    words={[
                      "Software Engineer",
                      "Problem Solver",
                      "Tech Enthousiast",
                      "Team player",
                    ]}
                    cursor
                    cursorColor="#348AA7"
                    delaySpeed={2500}
                    typeSpeed={45}
                    deleteSpeed={45}
                    loop={0}
                  />
                </Box>
              </Text>
            </GridItem>
          </SimpleGrid>

          <Box
            bottom="0"
            h="20"
            w="140%"
            pos="absolute"
            borderRadius="50% / 100%;"
            borderBottomLeftRadius="0"
            borderBottomRightRadius="0"
            bg="white"
          />
        </Center>
        <Center h="100vh" bg="white"></Center>
        <Center
          pos="relative"
          h="200vh"
          bg="radial-gradient(87.72% 153.49% at 97.34% 2.85%, #348AA7 0%, #102C4B 51.47%, #000020 99.52%)"
        >
          <Box
            top="0"
            h="20"
            w="140%"
            pos="absolute"
            borderRadius="50% / 100%;"
            borderTopLeftRadius="0"
            borderTopRightRadius="0"
            bg="white"
          />
          <Box
            bottom="0"
            h="20"
            w="140%"
            pos="absolute"
            borderRadius="50% / 100%;"
            borderBottomLeftRadius="0"
            borderBottomRightRadius="0"
            bg="white"
          />
        </Center>
        <Center h="100vh" bg="white"></Center>
      </main>
    </>
  );
}
